---
title: "codealongweek6"
author: "Mikel irigoyen"
date: "11/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
library(ggpubr)
library(broom)

```

```{r}
set.seed(1414)
gp_1 <- sample.int(20, size = 15, replace = TRUE)

set.seed(1424)
gp_2 <- sample.int(30, size = 15, replace = TRUE)

hist(gp_1)
hist(gp_2)

```

```{r}
my_mwu <- wilcox.test(gp_1, gp_2)
```

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point()
```

```{r}
# Linear model, stored as penguin_lm:
penguin_lm <- lm(body_mass_g ~ flipper_length_mm, data = penguins)

# Return the complete overview:
summary(penguin_lm)
```

```{r}
penguin_lm_tidy <- broom::tidy(penguin_lm)

# Get the intercept: 
penguin_int <- penguin_lm_tidy$estimate[1]
penguin_int

# Then to get the flipper_length coefficient:
penguin_coef <- penguin_lm_tidy$estimate[2]
penguin_coef

penguin_lm_out <- broom::glance(penguin_lm)
penguin_lm_out
```

```{r}
plot(penguin_lm)
```

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm",
              color = "red",
              size = 0.5,
              fill = "gray10",
              alpha = 0.5) +
  theme_light() +
  ggpubr::stat_regline_equation(label.x = 180, label.y = 5700)
```

```{r}
penguins_cor <- cor.test(penguins$flipper_length_mm, penguins$body_mass_g)
```

